apiVersion: v1
kind: Secret
metadata:
  name: service-ssl-certificates
type: Opaque
data:
  ca.crt: {{.Values.certs.ca_crt}}
  server.crt: {{.Values.certs.server_crt}}
  server.key: {{.Values.certs.server_key}}
