# SAMPLE CONFIG FILE
namespace: user-scottboag
k8s_1dot8_or_above: false
docker:
  registry: registry.ng.bluemix.net
  namespace: dlaas_dev
  image_prefix: dlaas-
  pullPolicy: Always
  imagePullSecret: bluemix-cr-ng
certs:
  ca_crt: DUMMY==
  server_crt: DUMMY=
  server_key: DUMMY
trainer:
  version: user-sboag
restapi:
  version: user-sboag
databroker:
  tag: user-sboag
  version: user-sboag
webui:
  version: user-sboag
ffdl-lcm:
  namespace: user-scottboag
  k8s_1dot8_or_above: false
  lcm:
    shared_volume_storage_class: ""
    has_static_volumes: false
    version: user-sboag
  learner:
    docker_namespace: dlaas_dev
    tag: user-sboag
  docker:
    registry: registry.ng.bluemix.net
    namespace: dlaas_dev
    image_prefix: dlaas-
    pullPolicy: Always
    imagePullSecret: bluemix-cr-ng
ffdl-model-metrics:
  namespace: user-scottboag
  k8s_1dot8_or_above: false
  trainingdata:
    version: user-sboag
  docker:
    registry: registry.ng.bluemix.net
    namespace: dlaas_dev
    image_prefix: dlaas-
    pullPolicy: Always
    imagePullSecret: bluemix-cr-ng
